# Comment settings to make the global config prevail. E.g. comment "debug: 1" switch to global config.
# The global config can be found in the custom library.
debug: 1
job:
  throttle: 5
build:
  buildEnvironment: 'test'
pr:
  buildEnabled: 1
  deployEnabled: 1
  buildEnvironment: 'prod'
  extra: 'tessie'