loglevel: 'TRACE'
job:
  throttle: 2
config:
  build:
    buildEnvironment: 'test'
  pr:
    buildEnabled: 1
    deployEnabled: 0
    buildEnvironment: 'stag'
  environments:
    generic:
      agent:
        k8:
          name: 'base+jenkins_builder+s_large'
    test:
      agent:
        k8:
          name: 'base+jenkins_builder+s_fast'
      