loglevel: 'DEBUG'
job:
  throttle: 2
config:
  build:
    buildEnvironment: 'dev'
  pr:
    buildEnabled: 1
    deployEnabled: 0
    buildEnvironment: 'test'
  environments:
    generic:
      agent:
        k8:
          name: 'base+jenkins_builder+s_micro'      