appFamily: 'wins'
appName: 'hello-world'
loglevel: 'TRACE'
job:
  throttle: 5
config:
  build:
    buildEnvironment: 'cicd_dev_only'
  pr:
    buildEnabled: 1
    deployEnabled: 0
    buildEnvironment: 'cicd_dev_only'
  environments:
    generic:
      # appNamePrefix: 'prefix-'
      # appNamePostfix: '-postfix'
      agent:
        name: 's_micro'
      dockerFile: 'Dockerfile.cicd'
    dev:
      name: 'Development'
      platformName: 'Local'
      platformOwner: 'CrossLogic'
      platformNamespace: 'na'

      gitCredentials: 'github.main.cicd.api.credentials'
      registryType: 'docker'
      registryUrl: 'registry.hub.docker.com'
      registrySpace: 'jmaclean'
      registryCredentials: 'registry.dockerhub.cicd.api.credentials'