loglevel: 'TRACE'
job:
  throttle: 1
config:
  agent:
    k8:
      name: 'base+jenkins_builder+s_micro'
  build:
    buildEnvironment: 'dev'
  pr:
    buildEnabled: 1
    deployEnabled: 0
    buildEnvironment: 'dev'
